### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/host-home#100]
### Overview
Create a 404 page that matches the styles of the site.

### Action Items

- [x] Create a 404 page, keeping it consistent with the site's styles
- [ ] Pass to front end to build

### Resources/Instructions
[Link to Figma with 404 mock](https://www.figma.com/file/c9NcMJwWjbFFqB4PWcKqFf/Site-Pages?node-id=0%3A1)
[Link to SPY Style Guide](https://docs.google.com/presentation/d/18aQwYEARwtl3HSq6rvV21MeyIPySsIQvLLNy0VhuiG4/edit?usp=sharing)

**Comment by timmalstead** [comment]
@c-fuchs I did a first draft of the 404 page, please let me know what you think.

I don't think it needs to be as verbose as the copy on the figma, nor do I think we need a button.

I can of course go closer to that if you want. Please let me know.

**Comment by c-fuchs** [comment]
@timmalstead that sounds fine, but can you paste a screenshot here? The site just directs me to the login when I try to get a 404

**Comment by timmalstead** [comment]
certainly. it should be deployed soon but here it is in the meantime.
![Screen Shot 2020-04-03 at 6 01 27 PM](https://user-images.githubusercontent.com/54044142/78415233-569f8480-75d5-11ea-85e6-e82aea8f86ad.png)

**Comment by c-fuchs** [comment]
Thanks, it looks great! closing this now.
