### ISSUE TITLE
Debug authentication in docker environment

### ISSUE THREAD

**Issue by arshiamasih** [hackforla/host-home#121]
**in the standard dev mode no docker localhost:8080**: i managed to get successfully authenticated.

- i 'money-patched' in those values into the react code (index.tsx in /src root). i signed up and created an account successfully.
- i did not click the green check mark in the pop up to say yes to authenticating after my credentials were created and within 30 seconds it kicked to the homepage with hello, user in the corner. after 45 seconds i pressed the green checkmark in the auth pop up then closed the pop up.
- received confirmation email
- the hard coded values were visible in the console. i refreshed a couple of times and my username appear in the corner finally, hello arshia.masih@gmail.com. i am authenticated. i don't know how to now un-authenticate myself for testing auth again. i tried deleting my cookie/local storage etc but that did not work.
- any visit to the site from this point on takes me directly to the home page.
- what i did differently: initially i believe i made the mistake yesterday of using quotes, instead of backticks. auth worked when values are monkey patched in with backticks.

**when i spin up docker and go to localhost:80 :** unable to authenticate.

- i am seeing different behavior here. though i am further along than what i was seeing 4/8
- now in the pop up i get a message that: there was a callback redirect uri mismatch, and that "The provided redirect_uri is not in the list of allowed callback URLs."
- values ARE showing in console, with the auth0 redirect as "http://localhost"
- when running without docker, the redirect value showed as http://localhost:8080. not sure why it is working in one environment and not the other.
- i tried hardcoding to http://localhost:80 and still same error as above.
- also important to note - if you have been authenticated outside of running in docker and are not authenticated in docker, the cookie must be cleared or you will get a 403 error. (edited) 

**RESOLUTION:** -> these have all been updated in the README by @timmalstead 

- @tylerthome added http://localhost to the supported URLs for redirect (for deployment on port 80).
- webpack configuration was causing conflict between the two .env files, all pertinent info now lives in the root .env (database & auth)
- script for react live update in docker requires webpack an initial production build

**Comment by lola3736** [comment]
@tylerthome please review the complexity and points label for accruacy.
