### ISSUE TITLE
Optimize dev environment

### ISSUE THREAD

**Issue by arshiamasih** [hackforla/host-home#122]
Support @tylerthome in further optimizing dev environment for rapid iteration outside of the container. 

- As of now the scripts to run locally have been set up by Tyler, but still need to ensure the local and docker environments remain aligned.
- @timmalstead and I are currently testing the local run on localhost:8080 (webpack watch + python server + mongodb) and will regroup 4/12 on next steps 
- Additionally we are exploring CI/CD options to test our builds on the Dev branch.

**Comment by c-fuchs** [comment]
Closing as this is done, except CI/CD which will become a separate issue
