### ISSUE TITLE
Create a style guide based on the SPY website

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/host-home#13]
### Overview
We need to match the look and feel of the SPY website. 

### Action Items
Document fonts, color schemes, and other design elements of the SPY website.

### Resources/Instructions
[Link to Figma Board](https://www.figma.com/file/Pc91SyV6Lu0D7kaw62FJLQ/SPY-Design-System)
[SPY website](http://www.safeplaceforyouth.org/)
Useful plugin to examine a site's elements without knowing code: [Whatruns](https://www.whatruns.com/)

[V1 of Style Guide](https://drive.google.com/file/d/1R2PeoZhtBDtCMpOTQ8Gp0LNvV0Ip2nMZ/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Logo
![banner4](https://user-images.githubusercontent.com/37763229/71703331-e0e30d00-2d88-11ea-977f-c6b52a4b20a6.jpg)

Top menu
<img width="1103" alt="Screen Shot 2020-01-02 at 5 41 25 PM" src="https://user-images.githubusercontent.com/37763229/71703010-551cb100-2d87-11ea-9746-d80de016e793.png">
<img width="1086" alt="Screen Shot 2020-01-02 at 5 43 30 PM" src="https://user-images.githubusercontent.com/37763229/71703071-a2991e00-2d87-11ea-9b44-7690efb96497.png">

Footer
<img width="1422" alt="Screen Shot 2020-01-02 at 5 47 16 PM" src="https://user-images.githubusercontent.com/37763229/71703140-07547880-2d88-11ea-93c3-18251d4a2774.png">

Buttons
<img width="316" alt="Screen Shot 2020-01-02 at 5 49 06 PM" src="https://user-images.githubusercontent.com/37763229/71703175-38cd4400-2d88-11ea-9804-d45bc102f859.png">

<img width="311" alt="Screen Shot 2020-01-02 at 5 49 58 PM" src="https://user-images.githubusercontent.com/37763229/71703192-53072200-2d88-11ea-9fdb-147a288f55c0.png">

Infographics
<img width="544" alt="Screen Shot 2020-01-02 at 5 52 02 PM" src="https://user-images.githubusercontent.com/37763229/71703277-a37e7f80-2d88-11ea-99e2-5e791d77c789.png">

Bullet and link styling
<img width="527" alt="Screen Shot 2020-01-02 at 5 55 23 PM" src="https://user-images.githubusercontent.com/37763229/71703391-21db2180-2d89-11ea-9698-eb793d24b8ba.png">

**Comment by ExperimentsInHonesty** [comment]
@AlexChh93 's [figma](https://www.figma.com/file/Pc91SyV6Lu0D7kaw62FJLQ/SPY-Design-System?node-id=0%3A1)

**Comment by c-fuchs** [comment]
@AlexChh93, let's create check mark and X icons for matching tables.

**Comment by ExperimentsInHonesty** [comment]
As per our meeting of 1/8 discussion.  
AlexChh93 - Please add a screenshot from the SPY site to show the logo in relationship to the menu in order for developers to be able to eyeball the ratio easily.  This would go on the Logo page of the style guide, in addition to the logo by itself.

**Comment by awadethomas** [comment]
**Creating a To-Do List**
- Create & refine dedicated areas for Typography (font to use & replacement font), Color, Buttons & Button States, All Icons, Nav Structure, Pre-made Elements

**Comment by ExperimentsInHonesty** [comment]
@c-fuchs notes from meeting 2/4: 
Complete style guide, update with new screenshots (e.g. check and “x” icons and colors), and put in its own, linkable location to be published on project page on HfLA site

**Comment by awadethomas** [comment]
Style guide is now more up-to-date. We added Forms, updated Button sizes, Logo spacing, & additional colors

**Comment by awadethomas** [comment]
As an idea of what we can do as a next: https://biings.design/#/

**Comment by c-fuchs** [comment]
Great! Would you put these into a style guide V1 powerpoint to hand off to SPY?

**Comment by ExperimentsInHonesty** [comment]
@awadethomas Will you be able to make this slide deck before Tuesday?

**Comment by c-fuchs** [comment]
Style Guide moved to [Google Drive](https://drive.google.com/file/d/1R2PeoZhtBDtCMpOTQ8Gp0LNvV0Ip2nMZ/view?usp=sharing)
