### ISSUE TITLE
Create Host Home Project Card for Website

### ISSUE THREAD

**Issue by harishlingam** [hackforla/host-home#74]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [ ]   Gather items
  - [ ]  600 x 400 image
     - [ ]  Alt image text
  - [ ] 1500 x 700 hero image (please do not put project title on hero image)
     - [ ]  Alt image text
  - [ ]  Name of project
  - [ ]  A blurb about your project
  - [ ]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [ ]  Project leadership names and GitHub/Slack handles
  - [ ]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [ ]  What you are looking for skills wise
  - [ ]  Partner(s)
  - [ ]  Location
  - [ ]  Status
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by cnk** [comment]
If you can get some (or hopefully all) of this information, I would love to make a card for this project.

**Comment by c-fuchs** [comment]
Hi there,

It looks like this issue was duplicated, so please see issue #81 and thanks for your help!
