### ISSUE TITLE
Make a team email address with autoforwarder

### ISSUE THREAD

**Issue by c-fuchs** [hackforla/host-home#93]
### Overview
Create a shared team email address that auto-forwards messages to each team member's personal email.

### Action Items
Create a team email address, hosthome@hackforla.org. 
Set up an auto forward to send messages to the personal emails of all team members

### Resources/Instructions
[Team roster with email addresses](https://docs.google.com/spreadsheets/d/1Qp0iLv5Bvafip9y8gu9AUy2d5800916ybJ4_YElmyYM/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@c-fuchs @tylerthome renamed this email to homeuniteus@hackforla.org
